---
title: 'Week 1: Electoral Competitiveness'
author: "Package Build"
date: "2024-09-08"
output: pdf_document
categories: []
tags: []
slug: "week-1-electoral-competitiveness"
---



```{r}
my_custom_theme <- 
  theme_light() + 
  theme(panel.border = element_blank(),
        plot.title = element_text(size = 15, hjust = 0.5), 
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 12),
        strip.text = element_text(size = 18),
        axis.line = element_line(colour = "black"),
        legend.position = "top",
        legend.text = element_text(size = 12),
        text = element_text(family = "Palatino")
        )

d_popvote |> 
  ggplot(aes(x = year, y = pv2p, color = party)) + 
  geom_line() + 
  scale_color_manual(values = c("dodgerblue4", "firebrick1")) + 
  my_custom_theme
```


```{r}
# Sequester shapefile of states from `maps` library.
states_map <- map_data("state")

# Read wide version of dataset that can be used to compare candidate votes with one another. 
d_pvstate_wide <- read_csv("clean_wide_state_2pv_1948_2020.csv")

# Merge d_pvstate_wide with state_map.
d_pvstate_wide$region <- tolower(d_pvstate_wide$state)

pv_map <- d_pvstate_wide |>
  filter(year == 2020) |>
  left_join(states_map, by = "region")

# Make map grid of state winners for each election year available in the dataset. 
pv_win_map <- pv_map |> 
  mutate(winner = ifelse(R_pv2p > D_pv2p, "republican", "democrat"))
  
pv_win_map |> 
  ggplot(aes(long, lat, group = group)) + 
  geom_polygon(aes(fill = winner)) +
  scale_fill_manual(values = c("dodgerblue4", "firebrick1")) + 
  my_custom_theme + theme(axis.line = element_blank()) + theme(panel.grid = element_blank()) + theme(axis.text = element_blank()) + theme(axis.title = element_blank()) + theme(axis.text.x = element_blank())

```

```{r}
d_pvstate_wide |> 
  filter(year >= 1980) |> 
  left_join(states_map, by = "region") |> 
  mutate(winner = ifelse(R_pv2p > D_pv2p, "republican", "democrat")) |> 
  ggplot(aes(long, lat, group = group)) +
  facet_wrap(facets = year ~.) + 
  geom_polygon(aes(fill = winner), color = "white") + 
  scale_fill_manual(values = c("dodgerblue4", "firebrick1")) + 
  my_custom_theme + theme(axis.line = element_blank()) + theme(panel.grid = element_blank()) + theme(axis.text = element_blank()) + theme(axis.title = element_blank()) + theme(axis.text.x = element_blank())
  ggtitle("Presidential Vote Share (1980-2020)") + 
  theme(strip.text = element_text(size = 12), 
        aspect.ratio = 1)
```

