---
title: 'Week 1: Electoral Competitiveness'
author: Package Build
date: '2024-09-09'
slug: week-1-electoral-competitiveness
categories: []
tags: []
---


```{r include=FALSE}
library(ggplot2)
library(maps)
library(tidyverse)

## set working directory here
# setwd("~")

####----------------------------------------------------------#
#### Read and clean presidential popular vote.
####----------------------------------------------------------#

# Read presidential popular vote. 
d_popvote <- read_csv("popvote_1948-2020.csv")

# Subset data to most recent past election year. 
d_popvote |> 
  filter(year == 2020) |> 
  select(party, candidate, pv2p)

# Pivot data to wide format with party names as columns and two-party vote share as values.
(d_popvote_wide <- d_popvote |>
    select(year, party, pv2p) |>
    pivot_wider(names_from = party, values_from = pv2p))

# Modify winner column to show "D" if Democrats win and "R" if Republicans win. 
(d_popvote_wide <- d_popvote_wide |> 
    mutate(winner = case_when(democrat > republican ~ "D",
                              TRUE ~ "R")))

# Summarize data with respect to winners. 
d_popvote_wide |> 
  group_by(winner) |>
  summarise(races = n())

```


```{r}

```


```{r}

####----------------------------------------------------------#
#### Visualize trends in national presidential popular vote. 
####----------------------------------------------------------#

# Visualize the two-party presidential popular over time. 
d_popvote |> 
  ggplot(aes(x = year, y = pv2p, color = party)) + 
  geom_line() + 
  scale_color_manual(values = c("dodgerblue4", "firebrick1")) + 
  theme_bw()

my_custom_theme <- 
  theme_light() + 
  theme(panel.border = element_blank(),
        plot.title = element_text(size = 15, hjust = 0.5), 
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 12),
        strip.text = element_text(size = 18),
        axis.line = element_line(colour = "black"),
        legend.position = "top",
        legend.text = element_text(size = 12),
        text = element_text(family = "Georgia"))

d_popvote |> 
  ggplot(aes(x = year, y = pv2p, color = party)) + 
  geom_line() + 
  scale_color_manual(values = c("dodgerblue4", "firebrick1")) + 
  my_custom_theme

  
```



```{r}

```

```{r}
# Merge d_pvstate_wide with state_map.
d_pvstate_wide$region <- tolower(d_pvstate_wide$state)

pv_map <- d_pvstate_wide |>
  filter(year == 2020) |>
  left_join(states_map, by = "region")

# Make map grid of state winners for each election year available in the dataset. 
pv_win_map <- pv_map |> 
  mutate(winner = ifelse(R_pv2p > D_pv2p, "republican", "democrat"))
  
pv_win_map |> 
  ggplot(aes(long, lat, group = group)) + 
  geom_polygon(aes(fill = winner)) + 
  scale_fill_manual(values = c("dodgerblue4", "firebrick1")) + 
  my_custom_theme()
```



```{r}
d_pvstate_wide |> 
  filter(year >= 1980) |> 
  left_join(states_map, by = "region", relationship = "many-to-many") |> 
  mutate(winner = ifelse(R_pv2p > D_pv2p, "republican", "democrat")) |> 
  ggplot(aes(long, lat, group = group)) +
  facet_wrap(facets = year ~.) + 
  geom_polygon(aes(fill = winner), color = "white") + 
  scale_fill_manual(values = c("dodgerblue4", "firebrick1")) + 
  theme_void() + 
  ggtitle("Presidential Vote Share (1980-2020)") + 
  theme(strip.text = element_text(size = 12), 
        aspect.ratio = 1)
```

